name: Compila con CMake, lint e docs generation

on:
  push:
    branches:
      - "dev"
      - "main"
  pull_request:
    branches:
      - "dev"
      - "main"
jobs:

  lint:
    runs-on: self-hosted
    steps:
      - run: pip install cpplint
      - run: cpplint --recursive .

  cppcheck:
    runs-on: self-hosted
    steps:
      - run: >
          cppcheck -q \
          --language=c++ \
          --template=gcc \
          --std=c++11 \
          --enable=all \
          --inline-suppr \
          ${{ github.workspace }}

  build:
    needs:
      - lint   #se ci sono errori non provo nemmeno a buildare
      - cppcheck
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - name: Set reusable strings
        id: strings
        shell: bash
        run: |
            echo "build-output-dir=${{ github.workspace }}/build" >> "$GITHUB_OUTPUT"

      - name: Configure CMake
        run: >
            cmake -B ${{ steps.strings.outputs.build-output-dir }} 
            -DCMAKE_CXX_COMPILER=g++ 
            -DCMAKE_C_COMPILER=gcc 
            -DCMAKE_BUILD_TYPE=Release 
            -S ${{ github.workspace }}

      - name: Build
        run: cmake --build ${{ steps.strings.outputs.build-output-dir }} --config Release

      - name: Test
        working-directory: ${{ steps.strings.outputs.build-output-dir }}
        run: ctest --build-config Release

  documentation:
    needs: build
    runs-on: self-hosted
    steps:
      - run: doxygen --version
      - run: doxygen docs/Doxyfile
      - run: mv docs/out/html public
